### PR TITLE
Add the SAP Continuous Integration and Delivery service

### PR DESCRIPTION
**Pull request by LindaSieb**
The final wording can be changed, but there is a service that offers CICD pipelines offered by SAP that we should link.

### CODE REVIEW

**Comment by annawenger20** [comment]
Boris, can you have a quick look? Thanks!

**Review by bzarske — DISMISSED** [review]
Very good find, Linda! Adding SAP CI+D service makes perfect sense - in parallel, we should also mention CTMS instead of CTS+, but for this, I'll have to involve Harald. Nevertheless, for CTS+, documentation for Neo is linked and at least, we should link the corresponding description for CF. So, please take over Linda's changes - and in addition, replace the current link "Transporting Multitarget Applications with CTS+" with the following link:
- Link text: Transporting Multitarget Applications in Cloud Foundry using CTS+
- URL: https://help.sap.com/docs/btp/sap-business-technology-platform/transporting-multitarget-applications-in-cloud-foundry-using-cts

Thanks a lot!

**Review by annawenger20 — APPROVED** [review]

**Comment by annawenger20** [comment]
Thanks, @LindaSieb - the update will be available on SAP Help Portal with the next release.

**Comment by LindaSieb** [comment]
> Thank you for your valuable content contribution, @LindaSieb! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/lindasieb

**Comment by LindaSieb** [comment]
> Thanks, @LindaSieb - the update will be available on SAP Help Portal with the next release.

Sweet, thanks!!

**Pull request merged**
